settings:
  # Global setting to enable / disable all storage sorters
  enabled: true

  # Frequency for checking sorters and sorting items into
  # target chests (in ticks)
  tick-frequency: 10

  # Maximum number of sorters a player can own. Can be overridden
  # by the perm united.storage.maxsorters.X, e.g.
  # united.storage.maxsorters.3 (highest limit will apply)
  default-max-sorters-per-player: 1

  # Maximum number of target chests a sorter can have. 
  # Can be overridden by the perm united.storage.maxtargets.X, e.g.
  # united.storage.maxtargets.10 (highest limit will apply)
  default-max-targets-per-sorter: 16

  # Maximum number of overflow chests a sorter can have. 
  # Can be overridden by the perm united.storage.maxoverflows.X, e.g.
  # united.storage.maxoverflows.5 (highest limit will apply)
  default-max-overflows-per-sorter: 4

  # Minimum distance between two sorter chests (in blocks)
  sorter-min-distance: 32

  # Maximum distance between a target chest and a sorter (in blocks).
  # Should always be smaller than sorter-min-distance to avoid
  # overlapping.
  # Can be overridden by the perm united.storage.maxdistance.X, e.g.
  # united.storage.maxdistance.64 (highest limit will apply)
  target-max-distance: 16

  # The time (in seconds) that an empty sorter chest remains enabled
  # before it is set to sleep mode. Sleeping chests don't sort items
  # unless woken up by interaction.
  idle-time-before-sleep: 30

  # If you have Towny installed, the placement of storage containers
  # will be checked against Towny permissions. If you don't use Towny,
  # these checks will be skipped
  towny:
    place-in-wilderness: false
    place-in-own-town: true
    place-in-trusted-town: true
    place-in-untrusted-town: false
  
  # If the last interaction with a sorter chest was longer ago than
  # purge-time-threshold (in seconds), the purge command will 
  # permanently delete the sorter and associated storage containers.
  # Use this to clear sorters of long-term inactive players.
  # Default is 90 days (7776000 seconds)
  purge-time-threshold: 7776000

  # Particles spawn in the center of the six block faces of a chest. 
  # The offset is the distance to the face.
  visualisation:
    sorter:
      particle: HAPPY_VILLAGER
      offset: 0.2
      count: 1
    target-auto:
      particle: SOUL_FIRE_FLAME
      offset: 0.2
      count: 1
    target-manual:
      particle: FLAME
      offset: 0.2
      count: 1
    overflow:
      particle: END_ROD
      offset: 0.2
      count: 1

messages:
  prefix: "<bold><red>U</red><white>L</white> Storage <dark_gray>Â» </dark_gray></bold>"

  # Usage help messages
  usage-cmd-create:
    - "<gray>Usage: /storage create <sorterchest | targetchest | overflowchest></gray>"
    - "<dark_gray>Turns the chest you are looking at into the desired type of storage container.</dark_gray>"
  usage-cmd-remove:
    - "<gray>Usage: /storage remove</gray>"
    - "<dark_gray>Removes the storage container settings from the chest you're looking at.</dark_gray>"
  usage-cmd-info:
    - "<gray>Usage: /storage info</gray>"
    - "<dark_gray>Shows information about the storage container chest you're looking at.</dark_gray>"
  usage-cmd-start:
    - "<gray>Usage: /storage start</gray>"
    - "<dark_gray>Starts the sorter chest you're looking at.</dark_gray>"
  usage-cmd-stop:
    - "<gray>Usage: /storage start</gray>"
    - "<dark_gray>Starts the sorter chest you're looking at.</dark_gray>"
  usage-cmd-toggledisplay:
    - "<gray>Usage: /storage toggledisplay</gray>"
    - "<dark_gray>Toggles particle display for your storage systems on and off.</dark_gray>"
  usage-cmd-item:
    - "<gray>Usage: /storage targetitem <add | remove | clear></gray>"
    - "<dark_gray>Manage the types of items that should be sorted into this chest.</dark_gray>"
  usage-cmd-item-add:
    - "<gray>Usage: /storage targetitem add <item_id></gray>"
    - "<dark_gray>Add a type of item that should be sorted into this chest.</dark_gray>"
  usage-cmd-item-remove:
    - "<gray>Usage: /storage targetitem remove <item_id></gray>"
    - "<dark_gray>Remove a type of item that should no longer be sorted into this chest.</dark_gray>"
  usage-cmd-item-clear:
    - "<gray>Usage: /storage targetitem clear</gray>"
    - "<dark_gray>Clear all target items and reset the target chest to automatic sorting by content.</dark_gray>"
  usage-cmd-admin-reload: "<gray>Usage: /unitedstorage reload</gray>"
  usage-cmd-admin-validate: "<gray>Usage: /unitedstorage validatedata</gray>"

  # error messages
  error-no-chest-in-los: "<red>You must look at a chest when using this command.</red>"
  error-sorter-too-close: "<red>This location is too close to another sorter chest.</red>"
  error-sorter-too-far: "<red>This location is too far away from a sorter chest.</red>"
  error-container-in-location: "<red>There is already a {storage-type} chest in this location.</red>"
  error-no-container-in-location: "<red>There is no storage chest in this location.</red>"
  error-no-sorter-in-location: "<red>There is no sorter chest in this location.</red>"
  error-overflow-full: '<red>The sorter at {sorter-loc} was disabled because overflow chests are full or missing. Clear the overflow and use "/storage sorter start" to reenable the sorting.</red>'
  error-remove-container: "<red>An error occured while trying to remove the storage container. Please contact an admin to review the log files.</red>"
  error-not-owner: "<red>You don't own this storage container.</red>"
  error-not-sorter-owner: "<red>You can't add this storage container because you don't own the sorter this will connect to.</red>"
  error-create-towny-permissions: "<red>You're not allowed to create a storage container in this location.</red>"
  error-too-many-sorters: "<red>You've already reached the maximum number of sorter chests you can own ({max}).</red>"
  error-too-many-targets: "<red>This sorter chest already has the maximum number of target chests connected ({max}).</red>"
  error-too-many-overflows: "<red>This sorter chest already has the maximum number of overflow chests connected ({max}).</red>"
  error-unknown-material: "<red>This item type is invalid.</red>"
  error-not-target-chest: "<red>This command only works on target chests.</red>"
  error-not-filter-item: "<red>This item type was not in the list of target items.</red>"
  error-cant-break-sorter: "<red>You can't break sorter chests. Remove the sorter with \"/storage remove\" first. WARNING: This will also remove all connected target and overflow chests.</red>"

  # warnings 
  warning-no-overflow: "<yellow>This sorter has no connected overflow chests. Create them with \"/storage create overflowchest\", or the sorter will not work correctly.</yellow>"
  warning-no-target: "<yellow>This sorter has no connected target chests. Create them with \"/storage create targetchest\", or the sorter will not work correctly.</yellow>"
  warning-unknown-item: "<yellow>Warning: The item name isn't recognized as a vanilla or custom item type.</yellow>"

  # command feedback
  success-create-sorter: "<dark_green>Successfully created a new sorter chest at {sorter-loc}</dark_green>"
  success-create-target: "<dark_green>Successfully created a new target chest for sorter at {sorter-loc}.</dark_green>"
  success-create-overflow: "<dark_green>Successfully created a new overflow chest for sorter at {sorter-loc}.</dark_green>"
  success-sorter-toggle: "<dark_green>Sorter set to {sorter-state}.</dark_green>"
  success-remove-container: "<dark_green>Storage container and all connected target and overflow chests removed.</dark_green>"
  success-item-add: "<dark_green>{material} has been added to the list of items that will be sorted into this target chest.</dark_green>"
  success-item-remove: "<dark_green>{material} has been removed from the list of items that will be sorted into this target chest.</dark_green>"
  success-item-clear: "<dark_green>List of target chest items cleared.</dark_green>"

  # info messages
  reload-info: "<white>UnitedStorage config reloaded.</white>"
  validation-complete-info: "<white>UnitedStorage data successfully validated.</white>"
  toggledisplay-info: "<white>Storage particle display is now {display-state}</white>"
  purge-complete-info: "<white>UnitedStorage data successfully purged.</white>"
  sorter-info:
    - "<aqua><bold>Storage Chest Info</bold></aqua>"
    - "<aqua>Type:</aqua><dark_aqua> Sorter chest</dark_aqua>"
    - "<aqua>Owner:</aqua><dark_aqua> {owner}</dark_aqua>"
    - "<aqua>State:</aqua><dark_aqua> {sorter-state}</dark_aqua>"
    - "<aqua>Connected target chests:</aqua><dark_aqua> {target-count}</dark_aqua>"
    - "<aqua>Connected overflow chests:</aqua><dark_aqua> {overflow-count}</dark_aqua>"
  target-info:
    - "<aqua><bold>Storage Chest Info</bold></aqua>"
    - "<aqua>Type:</aqua><dark_aqua> Target chest</dark_aqua>"
    - "<aqua>Owner:</aqua><dark_aqua> {owner}</dark_aqua>"
    - "<aqua>Mode:</aqua><dark_aqua> {mode}</dark_aqua>"
    - "<aqua>Items:</aqua><dark_aqua> {items}</dark_aqua>"
    - "<aqua>Connected sorter location:</aqua><dark_aqua> {sorter-loc}</dark_aqua>"
  overflow-info:
    - "<aqua><bold>Storage Chest Info</bold></aqua>"
    - "<aqua>Type:</aqua><dark_aqua> Overflow chest</dark_aqua>"
    - "<aqua>Owner:</aqua><dark_aqua> {owner}</dark_aqua>"
    - "<aqua>Connected sorter location:</aqua><dark_aqua> {sorter-loc}</dark_aqua>"
